version: '3'

services:
  mobo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mobo
      - mobo_static_volume:/mobo/static
      - mobo_media_volume:/mobo/media
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mobo_network
      - nginx_network
    depends_on:
      - mobo_postgresql
  mobo_postgresql:
    image: postgres:10
    container_name: mobo_postgresql
    volumes:
      - mobo_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - mobo_network

volumes:
  mobo_postgresql:
    external: true
  mobo_static_volume:
    external: true
  mobo_media_volume:
    external: true
networks:
  mobo_network:
    external: true
  nginx_network:
    external: true