# Generated by Django 3.2 on 2022-07-17 21:33

from django.db import migrations, models
import django.db.models.deletion
import product.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.utils.gallery_path, verbose_name='image')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='product.gallery', verbose_name='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='deleted')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('production_date', models.DateField(verbose_name='production_date')),
                ('size', models.FloatField(verbose_name='size')),
                ('panel', models.PositiveSmallIntegerField(choices=[(0, 'ips'), (1, 'amoled'), (2, 'super_amoled')], verbose_name='panel')),
                ('storage', models.PositiveSmallIntegerField(choices=[(0, '63 GB'), (1, '128 GB'), (2, '256 GB'), (3, '512 GB')], verbose_name='storage')),
                ('ram', models.PositiveSmallIntegerField(choices=[(0, '4 GB'), (1, '6 GB'), (2, '8 GB'), (3, '12 GB'), (4, '16 GB')], verbose_name='ram')),
                ('cpu', models.CharField(max_length=128, verbose_name='cpu')),
                ('camera', models.CharField(max_length=256, verbose_name='camera')),
                ('slefi_camera', models.CharField(max_length=256, verbose_name='selfi_camera')),
                ('operating_system', models.PositiveSmallIntegerField(choices=[(0, 'android'), (1, 'IOS')], verbose_name='operating_system')),
                ('price', models.IntegerField(verbose_name='price')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gallery', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'mobile',
                'verbose_name_plural': 'mobiles',
            },
        ),
    ]
