version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - mobo_static_volume:/mobo/static
      - mobo_media_volume:/mobo/media
    networks:
      - nginx_network

volumes:
  mobo_static_volume:
    external: true
  mobo_media_volume:
    external: true
networks:
  nginx_network:
    external: true